//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel_kadrov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Начальник.
    /// </summary>
    // *** Start programmer edit section *** (Начальник CustomAttributes)

    // *** End programmer edit section *** (Начальник CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Начальник : ICSSoft.STORMNET.DataObject
    {
        
        private string fIDсотрдника;
        
        private IIS.Otdel_kadrov.Сотрудник fСотрудник;
        
        // *** Start programmer edit section *** (Начальник CustomMembers)

        // *** End programmer edit section *** (Начальник CustomMembers)

        
        /// <summary>
        /// IDсотрдника.
        /// </summary>
        // *** Start programmer edit section *** (Начальник.IDсотрдника CustomAttributes)

        // *** End programmer edit section *** (Начальник.IDсотрдника CustomAttributes)
        [StrLen(255)]
        public virtual string IDсотрдника
        {
            get
            {
                // *** Start programmer edit section *** (Начальник.IDсотрдника Get start)

                // *** End programmer edit section *** (Начальник.IDсотрдника Get start)
                string result = this.fIDсотрдника;
                // *** Start programmer edit section *** (Начальник.IDсотрдника Get end)

                // *** End programmer edit section *** (Начальник.IDсотрдника Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Начальник.IDсотрдника Set start)

                // *** End programmer edit section *** (Начальник.IDсотрдника Set start)
                this.fIDсотрдника = value;
                // *** Start programmer edit section *** (Начальник.IDсотрдника Set end)

                // *** End programmer edit section *** (Начальник.IDсотрдника Set end)
            }
        }
        
        /// <summary>
        /// Начальник.
        /// </summary>
        // *** Start programmer edit section *** (Начальник.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Начальник.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Otdel_kadrov.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Начальник.Сотрудник Get start)

                // *** End programmer edit section *** (Начальник.Сотрудник Get start)
                IIS.Otdel_kadrov.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Начальник.Сотрудник Get end)

                // *** End programmer edit section *** (Начальник.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Начальник.Сотрудник Set start)

                // *** End programmer edit section *** (Начальник.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Начальник.Сотрудник Set end)

                // *** End programmer edit section *** (Начальник.Сотрудник Set end)
            }
        }
    }
}
