//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel_kadrov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Подразделения.
    /// </summary>
    // *** Start programmer edit section *** (Подразделения CustomAttributes)

    // *** End programmer edit section *** (Подразделения CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПодразделенияE", new string[0])]
    [View("ПодразделенияL", new string[0])]
    public class Подразделения : ICSSoft.STORMNET.DataObject
    {
        
        // *** Start programmer edit section *** (Подразделения CustomMembers)

        // *** End programmer edit section *** (Подразделения CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПодразделенияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПодразделенияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПодразделенияE", typeof(IIS.Otdel_kadrov.Подразделения));
                }
            }
            
            /// <summary>
            /// "ПодразделенияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПодразделенияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПодразделенияL", typeof(IIS.Otdel_kadrov.Подразделения));
                }
            }
        }
    }
}
