//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel_kadrov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расчет.
    /// </summary>
    // *** Start programmer edit section *** (Расчет CustomAttributes)

    // *** End programmer edit section *** (Расчет CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасчетE", new string[] {
            "IDсотрдника as \'I dсотрдника\'",
            "Начальник as \'Начальник\'",
            "Начальник.IDсотрдника as \'I dсотрдника\'"}, Hidden=new string[] {
            "Начальник.IDсотрдника"})]
    [MasterViewDefineAttribute("РасчетE", "Начальник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "IDсотрдника")]
    [View("РасчетL", new string[] {
            "IDсотрдника as \'I dсотрдника\'",
            "Начальник.IDсотрдника as \'I dсотрдника\'"})]
    public class Расчет : ICSSoft.STORMNET.DataObject
    {
        
        private string fIDсотрдника;
        
        private IIS.Otdel_kadrov.Начальник fНачальник;
        
        // *** Start programmer edit section *** (Расчет CustomMembers)

        // *** End programmer edit section *** (Расчет CustomMembers)

        
        /// <summary>
        /// IDсотрдника.
        /// </summary>
        // *** Start programmer edit section *** (Расчет.IDсотрдника CustomAttributes)

        // *** End programmer edit section *** (Расчет.IDсотрдника CustomAttributes)
        [StrLen(255)]
        public virtual string IDсотрдника
        {
            get
            {
                // *** Start programmer edit section *** (Расчет.IDсотрдника Get start)

                // *** End programmer edit section *** (Расчет.IDсотрдника Get start)
                string result = this.fIDсотрдника;
                // *** Start programmer edit section *** (Расчет.IDсотрдника Get end)

                // *** End programmer edit section *** (Расчет.IDсотрдника Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расчет.IDсотрдника Set start)

                // *** End programmer edit section *** (Расчет.IDсотрдника Set start)
                this.fIDсотрдника = value;
                // *** Start programmer edit section *** (Расчет.IDсотрдника Set end)

                // *** End programmer edit section *** (Расчет.IDсотрдника Set end)
            }
        }
        
        /// <summary>
        /// Расчет.
        /// </summary>
        // *** Start programmer edit section *** (Расчет.Начальник CustomAttributes)

        // *** End programmer edit section *** (Расчет.Начальник CustomAttributes)
        [PropertyStorage(new string[] {
                "Начальник"})]
        [NotNull()]
        public virtual IIS.Otdel_kadrov.Начальник Начальник
        {
            get
            {
                // *** Start programmer edit section *** (Расчет.Начальник Get start)

                // *** End programmer edit section *** (Расчет.Начальник Get start)
                IIS.Otdel_kadrov.Начальник result = this.fНачальник;
                // *** Start programmer edit section *** (Расчет.Начальник Get end)

                // *** End programmer edit section *** (Расчет.Начальник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расчет.Начальник Set start)

                // *** End programmer edit section *** (Расчет.Начальник Set start)
                this.fНачальник = value;
                // *** Start programmer edit section *** (Расчет.Начальник Set end)

                // *** End programmer edit section *** (Расчет.Начальник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РасчетE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасчетE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасчетE", typeof(IIS.Otdel_kadrov.Расчет));
                }
            }
            
            /// <summary>
            /// "РасчетL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасчетL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасчетL", typeof(IIS.Otdel_kadrov.Расчет));
                }
            }
        }
    }
}
