//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel_kadrov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудник.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудник CustomAttributes)

    // *** End programmer edit section *** (Сотрудник CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Сотрудник : ICSSoft.STORMNET.DataObject
    {
        
        private string fIDдолжности;
        
        private string fIDПодразделения;
        
        private IIS.Otdel_kadrov.Должности fДолжности;
        
        private IIS.Otdel_kadrov.Подразделения fПодразделения;
        
        // *** Start programmer edit section *** (Сотрудник CustomMembers)

        // *** End programmer edit section *** (Сотрудник CustomMembers)

        
        /// <summary>
        /// IDдолжности.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.IDдолжности CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.IDдолжности CustomAttributes)
        [StrLen(255)]
        public virtual string IDдолжности
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.IDдолжности Get start)

                // *** End programmer edit section *** (Сотрудник.IDдолжности Get start)
                string result = this.fIDдолжности;
                // *** Start programmer edit section *** (Сотрудник.IDдолжности Get end)

                // *** End programmer edit section *** (Сотрудник.IDдолжности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.IDдолжности Set start)

                // *** End programmer edit section *** (Сотрудник.IDдолжности Set start)
                this.fIDдолжности = value;
                // *** Start programmer edit section *** (Сотрудник.IDдолжности Set end)

                // *** End programmer edit section *** (Сотрудник.IDдолжности Set end)
            }
        }
        
        /// <summary>
        /// IDПодразделения.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.IDПодразделения CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.IDПодразделения CustomAttributes)
        [StrLen(255)]
        public virtual string IDПодразделения
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.IDПодразделения Get start)

                // *** End programmer edit section *** (Сотрудник.IDПодразделения Get start)
                string result = this.fIDПодразделения;
                // *** Start programmer edit section *** (Сотрудник.IDПодразделения Get end)

                // *** End programmer edit section *** (Сотрудник.IDПодразделения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.IDПодразделения Set start)

                // *** End programmer edit section *** (Сотрудник.IDПодразделения Set start)
                this.fIDПодразделения = value;
                // *** Start programmer edit section *** (Сотрудник.IDПодразделения Set end)

                // *** End programmer edit section *** (Сотрудник.IDПодразделения Set end)
            }
        }
        
        /// <summary>
        /// Сотрудник.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Должности CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Должности CustomAttributes)
        [PropertyStorage(new string[] {
                "Должности"})]
        [NotNull()]
        public virtual IIS.Otdel_kadrov.Должности Должности
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Должности Get start)

                // *** End programmer edit section *** (Сотрудник.Должности Get start)
                IIS.Otdel_kadrov.Должности result = this.fДолжности;
                // *** Start programmer edit section *** (Сотрудник.Должности Get end)

                // *** End programmer edit section *** (Сотрудник.Должности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Должности Set start)

                // *** End programmer edit section *** (Сотрудник.Должности Set start)
                this.fДолжности = value;
                // *** Start programmer edit section *** (Сотрудник.Должности Set end)

                // *** End programmer edit section *** (Сотрудник.Должности Set end)
            }
        }
        
        /// <summary>
        /// Сотрудник.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Подразделения CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Подразделения CustomAttributes)
        [PropertyStorage(new string[] {
                "Подразделения"})]
        [NotNull()]
        public virtual IIS.Otdel_kadrov.Подразделения Подразделения
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Подразделения Get start)

                // *** End programmer edit section *** (Сотрудник.Подразделения Get start)
                IIS.Otdel_kadrov.Подразделения result = this.fПодразделения;
                // *** Start programmer edit section *** (Сотрудник.Подразделения Get end)

                // *** End programmer edit section *** (Сотрудник.Подразделения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Подразделения Set start)

                // *** End programmer edit section *** (Сотрудник.Подразделения Set start)
                this.fПодразделения = value;
                // *** Start programmer edit section *** (Сотрудник.Подразделения Set end)

                // *** End programmer edit section *** (Сотрудник.Подразделения Set end)
            }
        }
    }
}
