//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel_kadrov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Увольнение.
    /// </summary>
    // *** Start programmer edit section *** (Увольнение CustomAttributes)

    // *** End programmer edit section *** (Увольнение CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Увольнение : ICSSoft.STORMNET.DataObject
    {
        
        private string fIDсотрдника;
        
        private string fIDподразделения;
        
        private IIS.Otdel_kadrov.Подразделения fПодразделения;
        
        private IIS.Otdel_kadrov.Должности fДолжности;
        
        private IIS.Otdel_kadrov.Начальник fНачальник;
        
        // *** Start programmer edit section *** (Увольнение CustomMembers)

        // *** End programmer edit section *** (Увольнение CustomMembers)

        
        /// <summary>
        /// IDподразделения.
        /// </summary>
        // *** Start programmer edit section *** (Увольнение.IDподразделения CustomAttributes)

        // *** End programmer edit section *** (Увольнение.IDподразделения CustomAttributes)
        [StrLen(255)]
        public virtual string IDподразделения
        {
            get
            {
                // *** Start programmer edit section *** (Увольнение.IDподразделения Get start)

                // *** End programmer edit section *** (Увольнение.IDподразделения Get start)
                string result = this.fIDподразделения;
                // *** Start programmer edit section *** (Увольнение.IDподразделения Get end)

                // *** End programmer edit section *** (Увольнение.IDподразделения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Увольнение.IDподразделения Set start)

                // *** End programmer edit section *** (Увольнение.IDподразделения Set start)
                this.fIDподразделения = value;
                // *** Start programmer edit section *** (Увольнение.IDподразделения Set end)

                // *** End programmer edit section *** (Увольнение.IDподразделения Set end)
            }
        }
        
        /// <summary>
        /// IDсотрдника.
        /// </summary>
        // *** Start programmer edit section *** (Увольнение.IDсотрдника CustomAttributes)

        // *** End programmer edit section *** (Увольнение.IDсотрдника CustomAttributes)
        [StrLen(255)]
        public virtual string IDсотрдника
        {
            get
            {
                // *** Start programmer edit section *** (Увольнение.IDсотрдника Get start)

                // *** End programmer edit section *** (Увольнение.IDсотрдника Get start)
                string result = this.fIDсотрдника;
                // *** Start programmer edit section *** (Увольнение.IDсотрдника Get end)

                // *** End programmer edit section *** (Увольнение.IDсотрдника Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Увольнение.IDсотрдника Set start)

                // *** End programmer edit section *** (Увольнение.IDсотрдника Set start)
                this.fIDсотрдника = value;
                // *** Start programmer edit section *** (Увольнение.IDсотрдника Set end)

                // *** End programmer edit section *** (Увольнение.IDсотрдника Set end)
            }
        }
        
        /// <summary>
        /// Увольнение.
        /// </summary>
        // *** Start programmer edit section *** (Увольнение.Должности CustomAttributes)

        // *** End programmer edit section *** (Увольнение.Должности CustomAttributes)
        [PropertyStorage(new string[] {
                "Должности"})]
        [NotNull()]
        public virtual IIS.Otdel_kadrov.Должности Должности
        {
            get
            {
                // *** Start programmer edit section *** (Увольнение.Должности Get start)

                // *** End programmer edit section *** (Увольнение.Должности Get start)
                IIS.Otdel_kadrov.Должности result = this.fДолжности;
                // *** Start programmer edit section *** (Увольнение.Должности Get end)

                // *** End programmer edit section *** (Увольнение.Должности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Увольнение.Должности Set start)

                // *** End programmer edit section *** (Увольнение.Должности Set start)
                this.fДолжности = value;
                // *** Start programmer edit section *** (Увольнение.Должности Set end)

                // *** End programmer edit section *** (Увольнение.Должности Set end)
            }
        }
        
        /// <summary>
        /// Увольнение.
        /// </summary>
        // *** Start programmer edit section *** (Увольнение.Начальник CustomAttributes)

        // *** End programmer edit section *** (Увольнение.Начальник CustomAttributes)
        [PropertyStorage(new string[] {
                "Начальник"})]
        [NotNull()]
        public virtual IIS.Otdel_kadrov.Начальник Начальник
        {
            get
            {
                // *** Start programmer edit section *** (Увольнение.Начальник Get start)

                // *** End programmer edit section *** (Увольнение.Начальник Get start)
                IIS.Otdel_kadrov.Начальник result = this.fНачальник;
                // *** Start programmer edit section *** (Увольнение.Начальник Get end)

                // *** End programmer edit section *** (Увольнение.Начальник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Увольнение.Начальник Set start)

                // *** End programmer edit section *** (Увольнение.Начальник Set start)
                this.fНачальник = value;
                // *** Start programmer edit section *** (Увольнение.Начальник Set end)

                // *** End programmer edit section *** (Увольнение.Начальник Set end)
            }
        }
        
        /// <summary>
        /// Увольнение.
        /// </summary>
        // *** Start programmer edit section *** (Увольнение.Подразделения CustomAttributes)

        // *** End programmer edit section *** (Увольнение.Подразделения CustomAttributes)
        [PropertyStorage(new string[] {
                "Подразделения"})]
        [NotNull()]
        public virtual IIS.Otdel_kadrov.Подразделения Подразделения
        {
            get
            {
                // *** Start programmer edit section *** (Увольнение.Подразделения Get start)

                // *** End programmer edit section *** (Увольнение.Подразделения Get start)
                IIS.Otdel_kadrov.Подразделения result = this.fПодразделения;
                // *** Start programmer edit section *** (Увольнение.Подразделения Get end)

                // *** End programmer edit section *** (Увольнение.Подразделения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Увольнение.Подразделения Set start)

                // *** End programmer edit section *** (Увольнение.Подразделения Set start)
                this.fПодразделения = value;
                // *** Start programmer edit section *** (Увольнение.Подразделения Set end)

                // *** End programmer edit section *** (Увольнение.Подразделения Set end)
            }
        }
    }
}
